config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :posts do
    resources :comments, only: [:create, :edit, :destroy]
  end

  resources :students

  resources :users do
    member do
      get :update_state
    end

  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :comment, :comments

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @new_comment = post.comments.new(comment_params)
    @new_comment.user = current_user

    respond_to do |format|
      if @new_comment.save
        format.html { redirect_to post, notice: I18n.t('controllers.comments.created') }
        format.json { render :show, status: :created, location: post }
      else
        format.html { redirect_to post, alert: I18n.t('controllers.comments.error') }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(post), notice: I18n.t('controllers.comments.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def post
    @post ||= Post.find(params[:post_id])
  end

  def comments
    @comments ||= post.comments.all
  end

  def comment
    @comment ||= comments.find(params[:id])
  end

  def comment_params
    params.fetch(:comment, {}).permit(:body)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.comment
  .comment-content
    .comment-head
      .comment-creator
        = link_to comment.user.name, user_path(comment.user)
      - if current_user_can_delete?(comment)
        .comment-menu
          /= '| '
          /= link_to( image_tag('edit_icon.png', size: '20x20', alt: 'Действие', title: 'Редактировать'), post_comment_path(comment.post, comment), method: :delete, data: {confirm: t('.destroy_confirm')})
          /= '   |   '
          = link_to( image_tag('delete_icon.png', size: '20x20', alt: 'Действие', title: 'Удалить'), post_comment_path(comment.post, comment), method: :delete, data: {confirm: t('.destroy_confirm')})
          /= ' |'
    .comment-body
      = comment.body
    .comment-published
      = l comment.created_at, format: :short

app/views/comments/_form.html.slim
= simple_form_for [post, comment] do |f|
  = render partial: 'partials/form_errors', locals: {model: post}
  .row
    .col-md-10
      = f.input :body, label: false
    .col-md-2.buffer-bottom
      = f.button :submit, class: 'btn btn-primary'