config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :posts do
    resources :comments, only: [:create, :edit, :destroy]
  end

  resources :students

  resources :users do
    member do
      get :update_state
    end

  end

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user

  validates :surname, presence: true, length: { maximum: 35 }
  validates :name, presence: true, length: { maximum: 35 }
  validates :birthday, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!

  helper_method :student, :students

  # GET /students
  # GET /students.json
  def index
    students
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if student.update(student_params)
        format.html { redirect_to student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: student }
      else
        format.html { render :edit }
        format.json { render json: student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def students
    @students ||= Student.all
  end

  def student
    @student ||= Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.fetch(:student, {}).permit(:name)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.slim
= simple_form_for student do |f|
  = render partial: 'partials/form_errors', locals: {model: student}
  div class="form-group"
    = f.input :surname
  div class="form-group"
    = f.input :name
  div class="form-group"
    = f.input :birthday

  div class="actions"
    = f.submit 'Сохранить', class: 'btn btn-primary'
    = ' или '
    = link_to 'вернуться', :back

app/views/students/edit.html.slim
h1 Editing student

== render 'form'

= link_to 'Show', @student
'  |
= link_to 'Back', students_path

app/views/students/index.html.slim
h1.text-center Ученики
br


- fields = ['Фамилия', 'Имя', 'День рождения', 'Родитель']

.container
  table data-toggle="table"
    thead
      tr
        th.text-center #
        - fields.each do |field|
          th data-sortable="true" = field
        th
    - students.each_with_index do |student, i|
      tr
        td.text-center = i+1
        td= student.surname
        td= student.name
        td= l student.birthday.to_date
        td= link_to student.user.name, user_path(student.user)
        td.text-center= link_to( image_tag('eye_icon.png', size: '20x20', alt: 'Действие', title: 'Просмотреть'), student )


= link_to 'New Student', new_student_path

app/views/students/new.html.slim
h1 New student

== render 'form'

= link_to 'Back', students_path

app/views/students/show.html.slim
.container-small
  div class="text-center"
    h1= "#{student.name} #{student.surname}"

  p= "День рождения: #{l student.birthday.to_date}"
  p
    = "Родитель: "
    = link_to student.user.name, user_path(student.user)



  /- if user == current_user
  /  p class="buffer-top"
  /    = link_to 'Редактировать профиль', edit_user_path(user), class: 'btn btn-default'