config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :posts do
    resources :comments, only: [:create, :edit, :destroy]
  end

  resources :students

  resources :users do
    member do
      get :update_state
    end

  end

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "SchoolHelper"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    /= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to 'Главная', root_path, class: 'navbar-brand'
            li= link_to 'Новости', posts_path
            li= link_to 'Ученики', students_path
            li= link_to "Link 3", "/path3"
            - if user_signed_in?
              li= link_to 'Пользователи', users_path if current_user.is_admin
              li= link_to 'Профиль', current_user
              li= link_to 'Выйти', destroy_user_session_path, method: :delete
            - else
              li= link_to 'Войти', new_user_session_path
              li= link_to 'Зарегистрироваться', new_user_registration_path

    .container
      .row
        .col-lg-12
          /= bootstrap_flash
            TODO: FLASH!!
          = yield
      /  .col-lg-3
      /    .well.sidebar-nav
      /      h3 Sidebar
      /      ul.nav.nav-list
      /        li.nav-header Sidebar
      /        li= link_to "Link 1", "/path1"
      /        li= link_to "Link 2", "/path2"
      /        li= link_to "Link 3", "/path3"

      /footer
      /  p &copy; Company 2017